### PR TITLE
tests: move dummy plugin code into testhelper package

### LINKED ISSUE #87: Restart Engine Launched Plugins on Crash
In reality, we need a certain robustness of the secrets engine. The simple default action on a plugin crashing would be to just remove it. However, that means we put the problem on the user to restart the engine. So in reality, users expect us to at least retry X times before a remove a plugin.

### PR DESCRIPTION
**Pull request by joe0BAB**
This PR moves the dummy plugin code into the `testhelper/dummy` directory and adds a bit more functionality to allow crashing plugins (needed in next PR).

### CODE REVIEW

File: engine/plugin_test.go [hunk 1]
```diff
@@ -149,17 +150,10 @@ func Test_newPlugin(t *testing.T) {
...
 				assert.ErrorContains(t, err, errGetSecret)
 				assert.NoError(t, p.Close())
 				r, err := parseOutput()
-				// TODO: investigate
-				// This keeps randomly failing on CI with:
-				// failed to unmarshal '': unexpected end of JSON input
-				//
-				// It means the plugin hasn't been shutdown yet though we believe it should have
-				// or the plugin somehow didn't manage to send stuff to STDOUT.
-				// Either way, when we try to parse what we believe is STDOUT, it's empty.
```
Comment (joe0BAB) [inline engine/plugin_test.go:162]: already fixed https://github.com/docker/secrets-engine/pull/134

File: internal/testhelper/dummy/dummy.go [hunk 2]
```diff
@@ -153,6 +159,9 @@ type dummyPluginResult struct {
 func (d *dummyPlugin) GetSecret(_ context.Context, request secrets.Request) (secrets.Envelope, error) {
 	d.m.Lock()
 	defer d.m.Unlock()
+	if d.cfg.CrashBehaviour != nil && len(d.result.GetSecret)+1 >= d.cfg.OnNthSecretRequest {
+		os.Exit(d.cfg.ExitCode)
+	}
```
Comment (joe0BAB) [inline internal/testhelper/dummy/dummy.go:164]: I need this later for testing the retry logic. Also this is the second main change, that the dummy plugin can be configured to crash on GetSecret requests.

**Review by Benehiko — APPROVED** [review]
