### PR TITLE
fix(engine): fix data race on shutdown

### LINKED ISSUE #273: Prepare Engine for Integration into Docker Desktop
We need to adjust the interface a bit to make integration with DD easier and comply with conventions there.

### LINKED ISSUE #280: Run unit tests with `-race` flag and fix all data race issues

### PR DESCRIPTION
**Pull request by joe0BAB**
Fixes a data race in the engine and enables `-race` flag for unit tests (except for engine, need to fix more data races first).

### CODE REVIEW

File: engine/engine.go [hunk 1]
```diff
@@ -51,26 +51,23 @@ func newEngine(ctx context.Context, cfg config) (engine, error) {
...
 	}()
 	return &engineImpl{
 		reg: reg,
 		close: sync.OnceValue(func() error {
 			defer cfg.listener.Close()
-			select {
-			case <-done:
-				return serverErr
-			default:
-			}
```
Comment (joe0BAB) [inline engine/engine.go:68]: I misunderstood how http.Server.Shutdown works. We can always call it regardless if some http.Server.Serve crashed. The only limitation is that we shouldn't call it more than once (which already prevent anyway)

**Review by Benehiko — APPROVED** [review]
