### PR TITLE
fix(ipc): initiate close when the binary stopped and avoid potential race between cmd.Start/cmd.Wait

### LINKED ISSUE #126: Bug: Flaky IPC unit tests on CI
To reproduce locally:
```
go test -v $(go list ./engine/...) -count 50 -failfast -timeout 30m
```

Example failures:

https://github.com/docker/secrets-engine/actions/runs/16438633979/job/46453921274

```
=== RUN   Test_newPlugin/plugin_returns_no_secret_but_an_error
time="2025-07-22T08:15:59Z" level=info msg="Reveived plugin registration request: dummy-plugin@my-version (pattern: foo-bar)"
time="2025-07-22T08:15:59Z" level=info msg="Plugin dummy-plugin@my-version registered successfully with pattern foo-bar"
time="2025-07-22T08:15:59Z" level=error msg="sending SIGINT/CTRL_BREAK_EVENT to plugin: os: process already finished"
time="2025-07-22T08:15:59Z" level=error msg="sending SIGKILL to plugin: os: process already finished"
    plugin_test.go:153: 
        	Error Trace:	/home/runner/work/secrets-engine/secrets-engine/engine/dummy.go:122
        	            				/home/runner/work/secrets-engine/secrets-engine/engine/plugin_test.go:153
        	Error:      	Expected value not to be nil.
        	Test:       	Test_newPlugin/plugin_returns_no_secret_but_an_error
```

### PR DESCRIPTION
**Pull request by joe0BAB**
This is a potential fix to #126 . We have to see that this actually fixes things, but it seems the flakiness is one specific test and digging into that revealed to potential issues:

- there are potential cases where the binary crashing would not result in cleanly shutting down everything
- there's a potential race between `cmd.Start` and `cmd.Wait` when the binary crashes immediately 

Observed again here: https://github.com/docker/secrets-engine/actions/runs/16470417176/job/46557962185?pr=131

Relevant logs:
```
--- PASS: Test_RegisterPlugin (0.00s)
    --- PASS: Test_RegisterPlugin/registration_fails (0.00s)
    --- PASS: Test_RegisterPlugin/registration_succeeds (0.00s)
time="2025-07-23T12:20:21Z" level=error msg="sending SIGINT/CTRL_BREAK_EVENT to plugin: os: process already finished"
time="2025-07-23T12:20:21Z" level=error msg="sending SIGKILL to plugin: os: process already finished"
=== NAME  Test_newPlugin/plugin_returns_no_secret_but_an_error
    plugin_test.go:153: 
        	Error Trace:	/home/runner/work/secrets-engine/secrets-engine/engine/dummy.go:122
        	            				/home/runner/work/secrets-engine/secrets-engine/engine/plugin_test.go:153
        	Error:      	Expected value not to be nil.
        	Test:       	Test_newPlugin/plugin_returns_no_secret_but_an_error
=== RUN   Test_newPlugin/plugin_ignoring_SIGINT_does_not_break_the_runtime
```

### CODE REVIEW

**Review by Benehiko — APPROVED** [review]

File: engine/plugin_test.go [hunk 1]
```diff
@@ -317,7 +325,7 @@ func Test_newExternalPlugin(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			socketPath := "test.sock"
+			socketPath := randString(6) + ".sock" // avoid socket name clashes with parallel running tests
```
Comment (joe0BAB) [inline engine/plugin_test.go:328]: This tiny thing might be another big cause for random failures here. Re-using a socket path for concurrently running tests, not a good idea 😅

**Review by Benehiko — APPROVED** [review]
