### PR TITLE
fix(ipc): server side hijacking logic

### LINKED ISSUE #149: Bug: yamux header issue
Occasionally, for externally launched plugins, the tests fail with this error:

```
time="2025-07-29T06:10:21Z" level=info msg="Registering plugin 3rd-party-plugin..."
2025/07/29 06:10:21 [ERR] yamux: Invalid protocol version: 1
time="2025-07-29T06:10:21Z" level=info msg="Plugin runtime stopped, plugin 3rd-party-plugin is shutting down..."
2025/07/29 06:10:21 [ERR] yamux: Failed to write header: write unix @->@: write: broken pipe
2025/07/29 06:10:21 [ERR] engine: registering dynamic plugin: failed to register plugin, ipc error: invalid protocol version
```
https://github.com/docker/secrets-engine/actions/runs/16588106197/job/46917341474?pr=142

So far we only have seen this happening for externally launched plugins. It seems we sometimes don't start with a clean state after the hijacking.

Either find out the cause or add some custom handshaking that is more robust and guarantees we start with a clean state.

Digging deeper into the hijacking topic reveals there are different ways to solve it:
* eg in dagger: https://github.com/dagger/dagger/blob/57403d72fcbcbcb55fcb616422e0c382f67bd396/engine/client/client.go#L949-L963 and https://github.com/dagger/dagger/blob/57403d72fcbcbcb55fcb616422e0c382f67bd396/engine/client/client.go#L864-L871 they don't really solve the hijacking but just do another request/dial which they than fully control
* or following the go reverse proxy: https://github.com/golang/go/blob/880ca333d708b957325b6ef4798699372d4c090e/src/net/http/httputil/reverseproxy.go#L768-L804

### PR DESCRIPTION
**Pull request by joe0BAB**
There were two issues with the current implementation:
* `net.Conn` is only guaranteed to be valid while the request handler hasn't returned. Ie., we need to make it wait for the code using it to finish before returning the request handler. Ownership of `net.Conn` can't be transferred out of the request handler as previously assumed.
* The response header needs to be written after the hijack.

Closes #149 .

Related issues:
* https://github.com/golang/go/issues/27408
* https://github.com/golang/go/issues/32314

### CODE REVIEW

File: internal/ipc/hijack.go [hunk 1]
```diff
@@ -59,9 +45,13 @@ func hijackRequest(conn net.Conn, timeout time.Duration) (net.Conn, error) {
 		return nil, fmt.Errorf("making hijack request: %s", err)
 	}
 
-	if err := conn.SetReadDeadline(time.Now().Add(timeout)); err != nil {
+	if err := conn.SetReadDeadline(time.Now().Add(4 * time.Second)); err != nil {
+		return nil, fmt.Errorf("clearing deadline: %w", err)
+	}
+	if err := conn.SetWriteDeadline(time.Now().Add(4 * time.Second)); err != nil {
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: aren't these just durations? do we need `time.Now()`?

File: internal/ipc/hijack.go [hunk 2]
```diff
@@ -126,6 +158,25 @@ func (h *hijackHandler) ServeHTTP(w http.ResponseWriter, _ *http.Request) {
...
+	if err := conn.SetReadDeadline(time.Now().Add(4 * time.Second)); err != nil {
+		h.logger.Errorf("SetReadDeadline error: %v", err)
+		conn.Close()
+		return
+	}
+	if err := conn.SetWriteDeadline(time.Now().Add(4 * time.Second)); err != nil {
+		h.logger.Errorf("SetWriteDeadline error: %v", err)
+		conn.Close()
+		return
+	}
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: same here

File: internal/ipc/hijack.go [hunk 3]
```diff
@@ -104,33 +105,46 @@ type CloseWriter interface {
...
+	// Flush the options to make sure the client sets the raw mode
+	brw.Flush()
+
+	resp := &http.Response{
+		StatusCode: http.StatusSwitchingProtocols,
+		Proto:      r.Proto,
+		Header:     w.Header(),
+	}
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: image

File: internal/ipc/hijack.go [hunk 4]
```diff
@@ -104,33 +105,57 @@ type CloseWriter interface {
...
+			Header:     w.Header(),
+		}
+		if err := resp.Write(conn); err != nil {
+			h.logger.Errorf("writing response: %v", err)
+			conn.Close()
+			return
+		}
+
+		h.cb(r.Context(), conn)
+		close(done)
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: this should be a defer I think

File: internal/ipc/hijack.go [hunk 5]
```diff
@@ -104,33 +105,57 @@ type CloseWriter interface {
...
+		brw.Flush()
+
+		resp := &http.Response{
+			StatusCode: http.StatusSwitchingProtocols,
+			Proto:      r.Proto,
+			Header:     w.Header(),
+		}
+		if err := resp.Write(conn); err != nil {
+			h.logger.Errorf("writing response: %v", err)
+			conn.Close()
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: you don't need conn.Close() here if we are already closing when we return the `ServeHTTP` func

File: internal/ipc/hijack.go [hunk 6]
```diff
@@ -104,33 +105,57 @@ type CloseWriter interface {
...
 
-	// Note: Be careful when trying to pass r.Context() in here.
-	// r.Context() gets cancelled when this function returns, but conn will live much longer which is misleading.
-	h.cb(conn)
+	defer conn.Close()
+
+	done := make(chan struct{})
+	go func() {
+		// Flush the options to make sure the client sets the raw mode
+		brw.Flush()
```
Comment (Benehiko) [inline internal/ipc/hijack.go]: are we sure about this flush now? we aren't doing anything with `brw` after this

File: internal/ipc/hijack.go [hunk 7]
```diff
@@ -104,33 +105,57 @@ type CloseWriter interface {
...
+
+		resp := &http.Response{
+			StatusCode: http.StatusSwitchingProtocols,
+			Proto:      r.Proto,
+			Header:     w.Header(),
```
Comment (Benehiko) [inline internal/ipc/hijack.go:140]: I don't think we are setting the `Connection: Upgrade` and `Upgrade: tcp` headers anymore.

File: internal/ipc/hijack.go (hunk 6 above)
Comment (joe0BAB) [reply internal/ipc/hijack.go]: indeed, it seems this should work: https://github.com/golang/go/blob/880ca333d708b957325b6ef4798699372d4c090e/src/net/http/httputil/reverseproxy.go#L797-L804

**Review by Benehiko — APPROVED** [review]
